import fs from "fs";
import path from "path";
import { sync as globSync } from "glob";
import { loadGettextParser } from "../loadGettextParser";
import { stableHashWithContext } from "../../common/hash";
import { loadConfig } from "../../common/config/loadConfig";

export type ConvertPoOptions = {
  input: string;
  output: string;
  topLevelKey?: string;
  indent?: number;
};

/**
 * Converts .po files to i18next compatible JSON format.
 *
 * The .po file should have been generated by the i18next-auto-keys CLI
 * where msgctxt contains the i18next key path and msgid contains the source text.
 */
export async function convertPoToJson(options: ConvertPoOptions): Promise<void> {
  const { input, output, topLevelKey, indent = 2 } = options;

  // Load config to get hash length
  const { config } = loadConfig();

  console.log(`📖 Converting .po file to i18next JSON: ${input}`);
  console.log(`📁 Output: ${output}`);

  // Check if input exists
  if (!fs.existsSync(input)) {
    throw new Error(`Input file not found: ${input}`);
  }

  // Load gettext parser
  const parser = await loadGettextParser();
  if (!parser?.po?.parse) {
    throw new Error("gettext-parser is required to parse .po files. Install it with: npm install gettext-parser");
  }

  // Read and parse .po file
  const poBuffer = fs.readFileSync(input);
  const catalog = parser.po.parse(poBuffer);

  // Extract translations
  const translations: Record<string, string> = {};
  let translationCount = 0;

  // Note: gettext-parser structure is translations[msgctxt][msgid] = entryData
  for (const [contextKey, contextEntries] of Object.entries(catalog.translations)) {
    for (const [msgid, entryData] of Object.entries(contextEntries as any)) {
      if (msgid === "" || !entryData) continue; // Skip header entry

      // We don't care about plural forms, so we take the first msgstr
      const msgstr = (entryData as any).msgstr[0] || "";
      const msgctxt = (entryData as any).msgctxt;

      // Skip untranslated entries
      if (!msgstr) {
        console.warn(`⚠️  Skipping untranslated key: ${msgctxt || msgid}`);
        continue;
      }

      // Generate hash from msgid + msgctxt (translation context)
      const key = stableHashWithContext(msgid, msgctxt, config.hashLength);

      // Use the generated hash as a flat key (no nesting)
      translations[key] = msgstr;
      translationCount++;
    }
  }

  console.log(`🔑 Processed ${translationCount} translations`);

  // Wrap under topLevelKey if specified (matches emit plugin behavior)
  let output_data: any = translations;
  if (topLevelKey) {
    output_data = { [topLevelKey]: translations };
  }

  // Ensure output directory exists
  const outputDir = path.dirname(output);
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Write JSON file
  const jsonContent = JSON.stringify(output_data, null, indent);
  fs.writeFileSync(output, jsonContent, "utf8");

  console.log(`✅ i18next JSON file generated: ${output}`);
}

/**
 * Converts multiple .po files to JSON format.
 * Useful for batch processing multiple language files.
 */
export async function convertMultiplePoToJson(options: {
  pattern: string;
  outputDir: string;
  topLevelKey?: string;
  indent?: number;
}): Promise<void> {
  const { pattern, outputDir, topLevelKey, indent = 2 } = options;

  console.log(`🔍 Scanning for .po files using pattern: ${pattern}`);

  // Find .po files
  const poFiles = globSync(pattern, { absolute: true });
  console.log(`📁 Found ${poFiles.length} .po files`);

  if (poFiles.length === 0) {
    console.warn("⚠️  No .po files found matching the pattern");
    return;
  }

  // Ensure output directory exists
  if (!fs.existsSync(outputDir)) {
    fs.mkdirSync(outputDir, { recursive: true });
  }

  // Process each .po file
  for (const poFile of poFiles) {
    const baseName = path.basename(poFile, ".po");
    const jsonFile = path.join(outputDir, `${baseName}.json`);

    try {
      await convertPoToJson({
        input: poFile,
        output: jsonFile,
        topLevelKey,
        indent,
      });
    } catch (error) {
      console.error(`❌ Error converting ${poFile}:`, error);
    }
  }

  console.log(`✅ Batch conversion completed. Output directory: ${outputDir}`);
}
